### ISSUE TITLE
OpenHAB app does not recover if connection to openHAB is lost

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.app#4]
If openHAB is restarted will the app is running it does not recover from the connection loss.

**Comment by DivineThreepwood** [comment]
Issue still exists. After inventing some hours, i figured out that the SSE Service we use does just recover from connection lost but once the server (in our case openhab) is shutting down, it broadcasts an "connection end" message which causes all client connections to shutdown its connection. Afterwards the SSE is down on client site and does not automatically reconnect after the server is up and running again. Therefore, same kind of connection reconnect has to be implemented in order to catch up the connection.

**Comment by DivineThreepwood** [comment]
fixed.
